version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - dotenvx
  - hono
  - JWKS
  - mydb
  - openapi
  - PGCW
  - quramy
  - tanstack
  - todos
  - yamatatsu
ignoreWords: []
import: []
